steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd server
        gcloud app deploy --quiet

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
